# Site settings
title: developers.testello.com
email: dev@testello.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "developers.testello.com" # the base hostname & protocol for your site
port: 4000

# Build settings
markdown: kramdown
